Repository projectdiscovery/goflags, pull requests merged in 2023-08, with the labels that each got.

#128 add EnumSliceVar flag
  .gitignore
  enum_slice_var.go
  enum_slice_var_test.go
  examples/basic/main.go
  goflags.go
  goflags_test.go
Labels: Type: Enhancement

#135 Fixing utils permissions
  go.mod
  go.sum
Labels: Type: Bug

#137 run test on win and osx
  .github/workflows/build-test.yml
Labels: Type: Maintenance

#130 add flag support act as flag with defaultValue or option with value
  dynamic_var.go
  examples/basic/main.go
  go.mod
Labels: Type: Enhancement
